version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp/
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/migrate.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
    - location: scripts/post_deploy_cleanup.sh
      timeout: 300
      runas: root
